apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: computerbugs
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  namespace: websites
spec:
  tls:
  - hosts:
    - computerbugs.com.au
    - www.computerbugs.com.au
    secretName: computerbugs-tls
  rules:
  - host: computerbugs.com.au
    http:
      paths:
      - path: /
        backend:
          serviceName: computerbugs
          servicePort: 80
  - host: www.computerbugs.com.au
    http:
      paths:
      - path: /
        backend:
          serviceName: computerbugs
          servicePort: 80